language: scala

dist: precise

scala:
- 2.11.11
- 2.12.2

jdk:
- oraclejdk8

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_86276aecec54_key -iv $encrypted_86276aecec54_iv -in secring.gpg.enc -out secring.gpg -d;
  fi
- export PATH=${PATH}:./vendor/bundle
#- if [ "$TRAVIS_SCALA_VERSION" = "2.12.2" ]; then
#    set -x;
#    DOCS_REPO="https://github.com/frees-io/freestyle-docs.git" ;
#    if [ $(git ls-remote $DOCS_REPO | grep "refs/heads/$TRAVIS_BRANCH" | wc -l) = 1 ] ; then
#        git clone --branch $TRAVIS_BRANCH --depth=1 $DOCS_REPO  ;
#    else
#        git clone --branch master --depth=1 $DOCS_REPO  ;
#    fi ;
#    set +x;
#  fi

install:
- if [ "$TRAVIS_SCALA_VERSION" = "2.12.2" ]; then
      rvm use 2.2.3 --install --fuzzy ;
      gem update --system ;
      gem install sass ;
      gem install jekyll -v 3.2.1 ;
  fi

script:
- sbt ++$TRAVIS_SCALA_VERSION test:fastOptJS
- sbt ++$TRAVIS_SCALA_VERSION test
#- if [ "$TRAVIS_SCALA_VERSION" = "2.12.2" ]; then
#     sbt ++$TRAVIS_SCALA_VERSION publishLocal;
#     cd freestyle-docs && sbt ++$TRAVIS_SCALA_VERSION "clean" "tut"  && cd ..;
#  fi

cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- find $HOME/.coursier/cache -name "*.lock" -type f -delete
